*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LYTFI00013TOP.                     " Global Data
  INCLUDE LYTFI00013UXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LYTFI00013F00                           . " subprograms
  INCLUDE LYTFI00013I00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LYTFI00013F...                     " Subprograms
* INCLUDE LYTFI00013O...                     " PBO-Modules
* INCLUDE LYTFI00013I...                     " PAI-Modules
