*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LYTRE00007TOP.                     " Global Data
  INCLUDE LYTRE00007UXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LYTRE00007F00                           . " subprograms
  INCLUDE LYTRE00007I00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LYTRE00007F...                     " Subprograms
* INCLUDE LYTRE00007O...                     " PBO-Modules
* INCLUDE LYTRE00007I...                     " PAI-Modules
