*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LYTRT00002TOP.                     " Global Data
  INCLUDE LYTRT00002UXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LYTRT00002F00                           . " subprograms
  INCLUDE LYTRT00002I00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LYTRT00002F...                     " Subprograms
* INCLUDE LYTRT00002O...                     " PBO-Modules
* INCLUDE LYTRT00002I...                     " PAI-Modules
